site_name: Catálogo ejercicios años anteriores
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
plugins:
  - search:
      lang: es
  - tags
  - macros
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra:
  search:
    boost:
      tags: 2
nav:
  - Inicio: index.md
  - Tags: tags.md
  - Exámenes:
    - "2012":
      - exams/2012/p1.md
      - exams/2012/p2.md
      - exams/2012/exam.md
      - exams/2012/extra.md
    - "2013":
      - exams/2013/p1.md
      - exams/2013/p1r.md
      - exams/2013/p2.md
      - exams/2013/extra.md
    - "2014":
      - exams/2014/p1.md
      - exams/2014/p1r.md
      - exams/2014/p2.md
      - exams/2014/extra.md
    - "2015":
      - exams/2015/p1.md
      - exams/2015/p1r.md
      - exams/2015/p2.md
      - exams/2015/extra.md
    - "2016":
      - exams/2016/p1.md
      - exams/2016/p1r.md
      - exams/2016/p2.md
      - exams/2016/extra.md
    - "2017":
      - exams/2017/p1.md
      - exams/2017/p1r.md
      - exams/2017/p2.md
      - exams/2017/extra.md
    - "2018":
      - exams/2018/p1.md
      - exams/2018/p1r.md
      - exams/2018/p2.md
      - exams/2018/extra.md
    - "2019":
      - exams/2019/p1.md
      - exams/2019/p1r.md
      - exams/2019/p2.md
      - exams/2019/pract.md
      - exams/2019/extra.md
    - "2021":
      - exams/2021/p1.md
      - exams/2021/p1r.md
      - exams/2021/p2.md
      - exams/2021/p2r.md
      - exams/2021/extra.md
    - "2022":
      - exams/2022/p1.md
      - exams/2022/p1r.md
      - exams/2022/p2.md
      - exams/2022/extra.md